defaults: {}
pull_request_rules:
  - name: Automatically merge successful scala-steward PRs
    conditions:
      - author=scala-steward
      - check-success=Build and Test (ubuntu-latest, 2.12.13, adopt@1.8)
      - check-success=Build and Test (ubuntu-latest, 2.13.5, adopt@1.8)
      - check-success=Build and Test (ubuntu-latest, 3.0.0-RC1, adopt@1.8)
      - check-success=Build and Test (ubuntu-latest, 3.0.0-RC2, adopt@1.8)
    actions:
        merge:
            strict: true
